// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW4TCfrlVh80cjWQ1FKu1SokypkQ68Doc',
    appId: '1:1097178954991:web:a18d6c3deb8a1a31bfaf1a',
    messagingSenderId: '1097178954991',
    projectId: 'buzz-hive-firebase',
    authDomain: 'buzz-hive-firebase.firebaseapp.com',
    storageBucket: 'buzz-hive-firebase.firebasestorage.app',
    measurementId: 'G-L34RB15HDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL67EU_-EvC4v_IE7wpk67rPkLUSiTSDY',
    appId: '1:1097178954991:android:4c3950482a6f929ebfaf1a',
    messagingSenderId: '1097178954991',
    projectId: 'buzz-hive-firebase',
    storageBucket: 'buzz-hive-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZoHBDvmSPSdElx1HFWU0rNs3_EmqQG4',
    appId: '1:1097178954991:ios:bb8b6703bb0f6141bfaf1a',
    messagingSenderId: '1097178954991',
    projectId: 'buzz-hive-firebase',
    storageBucket: 'buzz-hive-firebase.firebasestorage.app',
    androidClientId: '1097178954991-9f3nakil4d8f2jraioracavh2b5frt7q.apps.googleusercontent.com',
    iosClientId: '1097178954991-n1ajpa7lvi5kvsnj79cg60e8qe65fjf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzHiveApp',
  );
}
